name: flutter_starter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1

  # google_sign_in:
  # apple_sign_in:
  get: ^3.24.0
  get_storage: ^1.4.0

  # flutter_platform_widgets:
  flutter_sheet_localization: 2.0.1
  simple_gravatar:

dependency_overrides:
  analyzer: 0.40.1
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: 2.1.2
  build_runner: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
